CREATE TABLE "role" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE,
  updated_at TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE "scope" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE,
  updated_at TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT pk_scope PRIMARY KEY (id)
);

CREATE TABLE "user_role" (
  user_id bigint NOT NULL REFERENCES public.user(id),
  role_id bigint NOT NULL REFERENCES public.role(id)
);

CREATE TABLE "role_scope" (
  role_id bigint NOT NULL REFERENCES public.role(id),
  scope_id bigint NOT NULL REFERENCES scope(id)
);
